### ISSUE TITLE
not working...

### ISSUE THREAD

**Issue by Elmapul** [sketchfab/godot-plugin#12]
i'm using godot 3.1 stable
i tried to download the plugin from godot ->asset lib>sketchfab, but it didnt worked (also, it tries to replace default_env.tres, icon.png and Main.tscn wich is a bad pratice.

then i tried to download it from:
https://github.com/sketchfab/godot-plugin/releases/tag/v1.0.0

and got this error mensage:
não foi possível carregar o script complementar do caminho
'res://godot/addons/sketchfab/plugin.gd' parece haver um erro no código, por favor verifique a sintaxe.
translated to english it goes like this:
(failed to load the script from the path 'res://godot/addons/sketchfab/plugin.gd'  looks like there is an error on the code, please verify the sintax)

finally i tried to download it as an stand alone project and open it as an project, and got the following message:

 res://addons/sketchfab/Api.gd:150 - Parse Error: Identifier 'NOT_AUTHORIZED' is not declared in the current scope.
 modules/gdscript/gdscript.cpp:580 - Method/Function Failed, returning: ERR_PARSE_ERROR
 res://addons/sketchfab/Main.gd:26 - Parse Error: Could not fully preload the script, possible cyclic reference or compilation error. Use 'load()' instead if a cyclic reference is intended.
 modules/gdscript/gdscript.cpp:580 - Method/Function Failed, returning: ERR_PARSE_ERROR
 res://addons/sketchfab/Api.gd:150 - Parse Error: Identifier 'NOT_AUTHORIZED' is not declared in the current scope.
 modules/gdscript/gdscript.cpp:580 - Method/Function Failed, returning: ERR_PARSE_ERROR
 res://addons/sketchfab/Paginator.gd:7 - Parse Error: Could not fully preload the script, possible cyclic reference or compilation error. Use 'load()' instead if a cyclic reference is intended.
 modules/gdscript/gdscript.cpp:580 - Method/Function Failed, returning: ERR_PARSE_ERROR
 res://addons/sketchfab/plugin.gd:9 - Parse Error: Non-static function 'set_meta' can only be called from an instance.
 modules/gdscript/gdscript.cpp:580 - Method/Function Failed, returning: ERR_PARSE_ERROR
 scene/2d/canvas_item.cpp:478 - Condition ' !is_inside_tree() ' is true. returned: get_transform()
 scene/2d/canvas_item.cpp:966 - Condition ' !is_inside_tree() ' is true. returned: Rect2()
 scene/2d/canvas_item.cpp:966 - Condition ' !is_inside_tree() ' is true. returned: Rect2()
 scene/gui/control.cpp:2103 - Condition ' !is_inside_tree() ' is true.
 scene/2d/canvas_item.cpp:478 - Condition ' !is_inside_tree() ' is true. returned: get_transform()
 scene/2d/canvas_item.cpp:966 - Condition ' !is_inside_tree() ' is true. returned: Rect2()
 scene/gui/control.cpp:2074 - Condition ' !is_inside_tree() ' is true.
 ./scene/main/node.h:263 - Condition ' !data.tree ' is true. returned: __null
----------
 res://addons/sketchfab/Api.gd:150 - Parse Error: Identifier 'NOT_AUTHORIZED' is not declared in the current scope.
 modules/gdscript/gdscript.cpp:580 - Method/Function Failed, returning: ERR_PARSE_ERROR
 res://addons/sketchfab/Main.gd:26 - Parse Error: Could not fully preload the script, possible cyclic reference or compilation error. Use 'load()' instead if a cyclic reference is intended.
 modules/gdscript/gdscript.cpp:580 - Method/Function Failed, returning: ERR_PARSE_ERROR
 res://addons/sketchfab/Api.gd:150 - Parse Error: Identifier 'NOT_AUTHORIZED' is not declared in the current scope.
 modules/gdscript/gdscript.cpp:580 - Method/Function Failed, returning: ERR_PARSE_ERROR
 res://addons/sketchfab/Paginator.gd:7 - Parse Error: Could not fully preload the script, possible cyclic reference or compilation error. Use 'load()' instead if a cyclic reference is intended.
 modules/gdscript/gdscript.cpp:580 - Method/Function Failed, returning: ERR_PARSE_ERROR
 res://addons/sketchfab/plugin.gd:9 - Parse Error: Non-static function 'set_meta' can only be called from an instance.
 modules/gdscript/gdscript.cpp:580 - Method/Function Failed, returning: ERR_PARSE_ERROR

**Comment by noidexe** [comment]
I'm getting this similar error in Godot 3.2

```
SCRIPT ERROR: GDScript::reload: Parse Error: The identifier "NOT_AUTHORIZED" isn't declared in the current scope.
          At: res://addons/sketchfab/Api.gd:150
ERROR: reload: Method failed. Returning: ERR_PARSE_ERROR
   At: modules/gdscript/gdscript.cpp:576
SCRIPT ERROR: GDScript::reload: Parse Error: Couldn't fully preload the script, possible cyclic reference or compilation error. Use "load()" instead if a cyclic reference is intended.
          At: res://addons/sketchfab/Main.gd:26
ERROR: reload: Method failed. Returning: ERR_PARSE_ERROR
   At: modules/gdscript/gdscript.cpp:576
SCRIPT ERROR: GDScript::reload: Parse Error: The identifier "NOT_AUTHORIZED" isn't declared in the current scope.
          At: res://addons/sketchfab/Api.gd:150
ERROR: reload: Method failed. Returning: ERR_PARSE_ERROR
   At: modules/gdscript/gdscript.cpp:576
SCRIPT ERROR: GDScript::reload: Parse Error: Couldn't fully preload the script, possible cyclic reference or compilation error. Use "load()" instead if a cyclic reference is intended.
          At: res://addons/sketchfab/Paginator.gd:7
ERROR: reload: Method failed. Returning: ERR_PARSE_ERROR
   At: modules/gdscript/gdscript.cpp:576
SCRIPT ERROR: GDScript::reload: Parse Error: The identifier "NOT_AUTHORIZED" isn't declared in the current scope.
          At: res://addons/sketchfab/Api.gd:150
ERROR: reload: Method failed. Returning: ERR_PARSE_ERROR
   At: modules/gdscript/gdscript.cpp:576
```

**Comment by patrykkalinowski** [comment]
Not working in 3.2 for me, too.

Looks like the plugin has been abandoned immediately after release :/

**Comment by noidexe** [comment]
Fixed it. Man I wish I had tried it before. It was literally fixing just the first error. 
Go to Api.gd and replace line 150 with:
`		return SymbolicErrors.NOT_AUTHORIZED`

**Comment by noidexe** [comment]
Ok it seems this was already fixed in a different branch together with other issues. https://github.com/sketchfab/godot-plugin/tree/bug/updates-godot-plugin_D3D_5427

**Comment by noidexe** [comment]
![image](https://user-images.githubusercontent.com/526829/79673556-0d445d00-81b1-11ea-9398-e18ffb236bb6.png)

Yes, it's working fine. If Godot gets stuck after downloading an asset just wait. It's not the plugin's fault, it's the editor importer that's not granular enough in showing progress.

**Comment by patrykkalinowski** [comment]
Cool! After downloading plugin from the branch you linked everything works.

Is anyone from sketchfab monitoring this repo? Maybe it should be forked and maintained properly if they don't do it.

**Comment by noidexe** [comment]
It seems the PR is from a few days ago so I'd say yes

**Comment by loicSketchfab** [comment]
Hi Lads, and sorry for the delay coming back to this plugin.

As you have noticed, we have indeed just updated the release with [latest changes](https://github.com/sketchfab/godot-plugin/releases/latest), and will monitor this repo more closely from now on.

Thank you for your feedbacks, and please, do not hesitate for any suggestions you might have in the future. Any feedback will be welcome as we don't have any regular Godot user in the team (although the few tests I've been able to make with it have convinced me to give it a serious go some day)...

I'm closing this issue for now, but do not hesitate to re-open if needed :+1:
